apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
# automountServiceAccountToken: true
imagePullSecrets:
- name: regcred
---





# kubectl create secret docker-registry regcred --docker-server=registry449.azurecr.io --docker-username=registry449 --docker-password=7AfZQ6=IUeLPTjs3r96hhrgIZ2gWbfhL


# kubectl patch serviceaccount build-robot -p '{"imagePullSecrets": [{"name": "regcred"}]}'
